---
# tasks file for haproxy

- name: my package
  package:
        name: "haproxy"
        state: present

- name: my conf fiel copy
  template:
        src: "haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
  notify: "my haproxy restart"



- name: my service
  service:
        name: "haproxy"
        state: started


- name: my firwall
  firewalld:
       port: 8080/tcp
       permanent: yes
       state: enabled
       immediate: yes


